services:
  mongo:
    image: mongo:7
    container_name: catalog-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  catalogapi:
    build:
      context: .
      dockerfile: Catalog/Catalog.api/Dockerfile
    container_name: catalog-api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      DatabaseSettings__ConnectionString: mongodb://mongo:27017
      DatabaseSettings__DatabaseName: CatalogDb
      DatabaseSettings__ProductsCollection: Products
      DatabaseSettings__BrandsCollection: Brands
      DatabaseSettings__TypesCollection: Types
    volumes:
      # Mount الكود عشان Hot Reload
      - ./Catalog:/src/Catalog:ro
    depends_on:
      - mongo

volumes:
  mongo_data: